"""add item model

Revision ID: 68e9b8a12140
Revises: 001
Create Date: 2026-06-21 23:38:44.894644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e9b8a12140'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(), nullable=False),
    sa.Column('manual_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['uom.uom_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_item_code'), 'items', ['item_code'], unique=True)
    op.create_index(op.f('ix_items_manual_code'), 'items', ['manual_code'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.create_unique_constraint(None, 'branches', ['name'])
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.create_unique_constraint(None, 'suppliers', ['name'])
    op.drop_index(op.f('ix_uom_name'), table_name='uom')
    op.create_unique_constraint(None, 'uom', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uom', type_='unique')
    op.create_index(op.f('ix_uom_name'), 'uom', ['name'], unique=True)
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.drop_constraint(None, 'branches', type_='unique')
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=True)
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_manual_code'), table_name='items')
    op.drop_index(op.f('ix_items_item_code'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
