"""Add inventory transactions and branch stocks

Revision ID: 943ba4fce79f
Revises: 68e9b8a12140
Create Date: 2026-06-21 17:30:53.842575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943ba4fce79f'
down_revision: Union[str, None] = '68e9b8a12140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_stocks',
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='chk_branch_stock_quantity'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('branch_id', 'item_id')
    )
    op.create_index('ix_bstock_item', 'branch_stocks', ['item_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('document_no', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reference_type IN ('stock_in', 'outbound', 'transfer', 'opname', 'initial_load', 'manual', 'system')", name='chk_inv_ref_type'),
    sa.CheckConstraint("transaction_type IN ('IN', 'OUT', 'TRANSFER_OUT', 'TRANSFER_IN', 'ADJUSTMENT_PLUS', 'ADJUSTMENT_MINUS')", name='chk_inv_tx_type'),
    sa.CheckConstraint('quantity > 0', name='chk_inv_tx_quantity'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_invtx_branch_created', 'inventory_transactions', ['branch_id', 'created_at'], unique=False)
    op.create_index('ix_invtx_created_brin', 'inventory_transactions', ['created_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_invtx_document_no', 'inventory_transactions', ['document_no'], unique=False, postgresql_where=sa.text('document_no IS NOT NULL'))
    op.create_index('ix_invtx_item_branch', 'inventory_transactions', ['item_id', 'branch_id'], unique=False)
    op.create_index('ix_invtx_reference', 'inventory_transactions', ['reference_type', 'reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invtx_reference', table_name='inventory_transactions')
    op.drop_index('ix_invtx_item_branch', table_name='inventory_transactions')
    op.drop_index('ix_invtx_document_no', table_name='inventory_transactions', postgresql_where=sa.text('document_no IS NOT NULL'))
    op.drop_index('ix_invtx_created_brin', table_name='inventory_transactions', postgresql_using='brin')
    op.drop_index('ix_invtx_branch_created', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index('ix_bstock_item', table_name='branch_stocks')
    op.drop_table('branch_stocks')
    # ### end Alembic commands ###
