"""opname enhancements

Revision ID: cfd8947d315e
Revises: d9bcc51a8bf1
Create Date: 2026-06-27 04:54:03.411428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd8947d315e'
down_revision: Union[str, None] = 'd9bcc51a8bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_opname_sessions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('chk_opname_status', 'stock_opname_sessions', type_='check')
    op.create_check_constraint('chk_opname_status', 'stock_opname_sessions', "status IN ('draft', 'completed', 'canceled')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_opname_sessions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('chk_opname_status', 'stock_opname_sessions', type_='check')
    op.create_check_constraint('chk_opname_status', 'stock_opname_sessions', "status IN ('draft', 'completed')")
    # ### end Alembic commands ###
