"""add_transfers_and_stock_opname

Revision ID: d9bcc51a8bf1
Revises: dfcd698e0120
Create Date: 2026-06-23 07:21:27.245321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bcc51a8bf1'
down_revision: Union[str, None] = 'dfcd698e0120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_opname_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'completed')", name='chk_opname_status'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_stock_opname_sessions_branch_id'), 'stock_opname_sessions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_opname_sessions_category_id'), 'stock_opname_sessions', ['category_id'], unique=False)
    op.create_index(op.f('ix_stock_opname_sessions_status'), 'stock_opname_sessions', ['status'], unique=False)
    op.create_table('transfers',
    sa.Column('transfer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_number', sa.String(), nullable=False),
    sa.Column('source_branch_id', sa.Integer(), nullable=False),
    sa.Column('dest_branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_by', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'in_transit', 'received', 'cancelled')", name='chk_transfer_status'),
    sa.CheckConstraint('source_branch_id != dest_branch_id', name='chk_transfer_branches'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dest_branch_id'], ['branches.branch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipped_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_branch_id'], ['branches.branch_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_index(op.f('ix_transfers_dest_branch_id'), 'transfers', ['dest_branch_id'], unique=False)
    op.create_index(op.f('ix_transfers_source_branch_id'), 'transfers', ['source_branch_id'], unique=False)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_number'), 'transfers', ['transfer_number'], unique=True)
    op.create_table('stock_opname_lines',
    sa.Column('line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('system_quantity', sa.Integer(), nullable=False),
    sa.Column('physical_quantity', sa.Integer(), nullable=False),
    sa.Column('variance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('physical_quantity >= 0', name='chk_opname_physical_quantity'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['stock_opname_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id'),
    sa.UniqueConstraint('session_id', 'item_id', name='uq_opname_session_item')
    )
    op.create_index(op.f('ix_stock_opname_lines_item_id'), 'stock_opname_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_opname_lines_session_id'), 'stock_opname_lines', ['session_id'], unique=False)
    op.create_table('transfer_lines',
    sa.Column('line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sent_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=True),
    sa.Column('variance_notes', sa.Text(), nullable=True),
    sa.Column('variance_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('received_quantity >= 0 OR received_quantity IS NULL', name='chk_transfer_received_quantity'),
    sa.CheckConstraint('sent_quantity > 0', name='chk_transfer_sent_quantity'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.transfer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id'),
    sa.UniqueConstraint('transfer_id', 'item_id', name='uq_transfer_session_item')
    )
    op.create_index(op.f('ix_transfer_lines_item_id'), 'transfer_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_transfer_lines_transfer_id'), 'transfer_lines', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_lines_transfer_id'), table_name='transfer_lines')
    op.drop_index(op.f('ix_transfer_lines_item_id'), table_name='transfer_lines')
    op.drop_table('transfer_lines')
    op.drop_index(op.f('ix_stock_opname_lines_session_id'), table_name='stock_opname_lines')
    op.drop_index(op.f('ix_stock_opname_lines_item_id'), table_name='stock_opname_lines')
    op.drop_table('stock_opname_lines')
    op.drop_index(op.f('ix_transfers_transfer_number'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_source_branch_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_dest_branch_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_stock_opname_sessions_status'), table_name='stock_opname_sessions')
    op.drop_index(op.f('ix_stock_opname_sessions_category_id'), table_name='stock_opname_sessions')
    op.drop_index(op.f('ix_stock_opname_sessions_branch_id'), table_name='stock_opname_sessions')
    op.drop_table('stock_opname_sessions')
    # ### end Alembic commands ###
