"""add_stock_in_and_outbound

Revision ID: dfcd698e0120
Revises: 943ba4fce79f
Create Date: 2026-06-22 09:53:04.690073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcd698e0120'
down_revision: Union[str, None] = '943ba4fce79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('fulfilled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'completed', 'cancelled')", name='chk_outbound_status'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_outbound_sessions_branch_id'), 'outbound_sessions', ['branch_id'], unique=False)
    op.create_table('stock_in_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('supplier_invoice_no', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'completed', 'cancelled')", name='chk_stock_in_status'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_stock_in_sessions_branch_id'), 'stock_in_sessions', ['branch_id'], unique=False)
    op.create_table('outbound_lines',
    sa.Column('line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_outbound_line_quantity'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['outbound_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id'),
    sa.UniqueConstraint('session_id', 'item_id', name='uq_outbound_session_item')
    )
    op.create_index(op.f('ix_outbound_lines_item_id'), 'outbound_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_outbound_lines_session_id'), 'outbound_lines', ['session_id'], unique=False)
    op.create_table('stock_in_lines',
    sa.Column('line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_stock_in_line_quantity'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['stock_in_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id'),
    sa.UniqueConstraint('session_id', 'item_id', name='uq_stock_in_session_item')
    )
    op.create_index(op.f('ix_stock_in_lines_item_id'), 'stock_in_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_in_lines_session_id'), 'stock_in_lines', ['session_id'], unique=False)
    op.drop_index(op.f('ix_invtx_created_brin'), table_name='inventory_transactions', postgresql_using='brin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invtx_created_brin'), 'inventory_transactions', ['created_at'], unique=False, postgresql_using='brin')
    op.drop_index(op.f('ix_stock_in_lines_session_id'), table_name='stock_in_lines')
    op.drop_index(op.f('ix_stock_in_lines_item_id'), table_name='stock_in_lines')
    op.drop_table('stock_in_lines')
    op.drop_index(op.f('ix_outbound_lines_session_id'), table_name='outbound_lines')
    op.drop_index(op.f('ix_outbound_lines_item_id'), table_name='outbound_lines')
    op.drop_table('outbound_lines')
    op.drop_index(op.f('ix_stock_in_sessions_branch_id'), table_name='stock_in_sessions')
    op.drop_table('stock_in_sessions')
    op.drop_index(op.f('ix_outbound_sessions_branch_id'), table_name='outbound_sessions')
    op.drop_table('outbound_sessions')
    # ### end Alembic commands ###
